### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by rhaynes74** [Exr0nProjects/obsidian-sage#2]
Hi folks, I receive a couple of errors when I build the plugin:

main.ts:7:27 - error TS7016: Could not find a declaration file for module 'urlsafe-base64'. '/Users/rhaynes/Dropbox/Dendron4/vault/.obsidian/plugins/obsidian-sage/node_modules/urlsafe-base64/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/urlsafe-base64` if it exists or add a new declaration (.d.ts) file containing `declare module 'urlsafe-base64';`

7 import URLSafeBase64 from 'urlsafe-base64';
                            ~~~~~~~~~~~~~~~~

main.ts:207:26 - error TS2552: Cannot find name 'Prompt'. Did you mean 'prompt'?

207             if (err) new Prompt(`Failed to create SageMathCell permalink: ${err}`);
                             ~~~~~~

**Comment by Exr0n** [comment]
So sorry, development is slow right now. I'll let you know when I have a fix!

**Comment by Exr0n** [comment]
Hey @rhaynes74 thanks for checking the plugin out! I guess I thought I had tested the new changes but didn't. It should be fixed now (and I remembered to include the `main.js` file in the repo too :O )

Please let me know if you're able to get it working!

**Comment by rhaynes74** [comment]
Thanks!

Sincerely,

Dr. Ronald D. Haynes
Professor, Department of Mathematics and Statistics
Chair, MSc and Phd Scientific Computing Programs
Memorial University of Newfoundland

We acknowledge that the lands on which Memorial University’s campuses are situated are in the traditional territories of diverse Indigenous groups, and we acknowledge with respect the diverse histories and cultures of the Beothuk, Mi’kmaq, Innu, and Inuit of this province.

**Comment by 1C0D** [comment]
that's huge!

**Comment by Exr0n** [comment]
Closing because it seems to be working. Please re-open another issue if you encounter more trouble!
